### PR TITLE
Updates to OEP Readme

### PR DESCRIPTION
**Pull request by mikera**
Minor edits:
- Add @mikera for marketplace specialisation
- Update table to include new OEPs

### CODE REVIEW

**Comment by kremalicious** [comment]
was this made obsolete by #101 and #104?

**Comment by mikera** [comment]
Hi @kremalicious Some of it superseded by #101, have updated to reflect this. 

#104 we will have to revert I think, these need to be included.

**Comment by kremalicious** [comment]
So #108 includes everything from this PR here? Why open a new PR then?

**Comment by H34D** [comment]
we have conflicts here, is this still needed or can we close this PR? @mikera

**Pull request closed without merging**
